name: clublab_lite
description: "ClubLab-lite mobile project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl:

  # Core
  get_it: 8.0.2
  provider: 6.1.2
  go_router: 14.4.1

  # Storage
  shared_preferences: 2.3.2
  flutter_secure_storage: 9.2.2

  # State management
  control: 0.2.0

  # Network
  http: 1.2.2

  # UI
  cupertino_icons: 1.0.8
  flutter_screenutil: 5.9.3
  mask_text_input_formatter: 2.9.0
  flutter_svg: 2.0.13
  pin_code_fields: 8.0.1

  # Utils
  logger: 2.4.0
  path_provider:
  path:
  share_plus: 10.0.2
  collection:

  # Code generation
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: 4.0.0
  dart_code_metrics_presets: 2.16.0

  # Code generation
  build_runner:
  flutter_gen_runner:
  json_serializable:

  # Utils
  # Usage: dart run rename setAppName --targets ios,android --value "ClubLab lite"
  # Usage: dart run rename setBundleId --targets ios,android --value "biz.lite.clublab"
  rename: 3.0.2
  flutter_launcher_icons: 0.14.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_gen:
  output: lib/app/assets/
  integrations:
    flutter_svg: true

# Usage: dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  adaptive_icon_background: "assets/images/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  ios: true
  remove_alpha_ios: true
